name: "🐞 Bug"
description: "버그 수정"
title: "🐞 Bug: [파트명] ... 버그 수정"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 🐛 문제 설명
      description: 어떤 문제가 발생했는지 자세히 작성해주세요.
      value: |
        아래 예시를 참고해 작성해주세요:
        - 특정 상황에서 버튼 클릭 시 화면이 멈춤
        - 모바일 환경에서 UI가 깨져 보임
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔍 재현 방법
      description: 문제를 어떻게 재현할 수 있는지 단계별로 작성해주세요.
      value: |
        예시:
        1. 로그인 후 장바구니 페이지로 이동
        2. 상품 추가 버튼 클릭
        3. 오류 메시지 발생
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 해야 할 일
      description: 체크리스트로 작업 내용을 작성해주세요.
      value: |
        예시:
        - [ ] 문제 원인 분석
        - [ ] 오류 재현 테스트
        - [ ] 코드 수정
        - [ ] QA 테스트 진행
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고할 로그, 스크린샷, 영상이 있으면 첨부해주세요.
      value: |
        예시:
        - 오류 로그 캡처
        - 문제 상황 스크린샷
